### ISSUE TITLE
proposal: Return values: usage + UNSUPPORTED vs UNSUPPORTED

### ISSUE THREAD

**Issue by aleksiklasila** [ouspg/trytls#110]
The value printed - if a stub **does not "support"** the number of arguments given - is not uniform among all the stubs. Should we consider choosing one of the following proposals.

**when not supported:**
1. A stub either Returns **always** UNSUPPORTED?
2. Or should the stub return UNSUPPORTED **only when given 2(host + port) or 3(host + port + ca-bundle)** arguments and usage **other times**?

which one should we choose (or other proposals)?
- [x] 1. UNSUPPORTED
- [ ] 2. usage(argc < 2 or argc > 3) and UNSUPPORTED(2 <= argc <= 3)

**Comment by ikisusi** [comment]
There is always an unspecified area outside the conforming calling convention and proper environmental conditions (enough memory, enough cpu time allowed, ...). Current calling convention specifies the positive space, ie. what should happen when calling convention is followed and the corresponding return values (VERIFY FAILURE, VERIFY SUCCESS, UNSUPPORTED) and corresponding exit value (0). In all other cases, ie. when calling convention is violated, stub runs out of memory, lightning strikes or machine catches fire then stub should just _err_, explain its diagnosis for erring if sensible and return non zero exit value. We really can't specify all the reasons and outcomes for erring so I think we should stick to the current convention of erring (with optional explanation) and a non-zero exit value.

**Comment by ikisusi** [comment]
A furthernote, what is **important** is that under no circumstances should the stubs return `VERIFY SUCCESS` and exit value 0 when they err for whatever reason, including broken calling convention.

**Comment by jviide** [comment]
Just requiring the stub to exit with a non-zero exit code (with optional reason text) when an unexpected number of arguments has been given sounds sensible. However we probably shouldn't _require_ the stub writers to print out an usage string.

**Comment by aleksiklasila** [comment]
Well, i wasn't thinking about specifying all the reasons and outcomes for erring. I was just thinking that maybe there should be some expected behavior/pattern - which could not be too easily mistaken to something entirely different - if no correct number of arguments were given. Because by doing so it would be easier to semi-automatically identify 'how' to run the stub (name of which is not always exactly known), e.g. "java Run.java -> _, java Run.class -> _, java Run -> UNSUPPORTED" -> java Run .. is the 'correct' way of executing the stub (this is how it's currently implemented in simplerunner([run](https://github.com/ouspg/trytls/blob/master/runners/bashtls/shared/simplerunner/run), [sr](https://github.com/ouspg/trytls/blob/master/runners/bashtls/shared/simplerunner/sr)). The scripts can of course be edited to match the wanted behavior but some expected output (exit value (not so good because java Run.java or something might return the same exit value as well) or stdout or something) might be great. If the UNSUPPORTED was printed that would also mean that there might be a change of making the usage of certificates a little bit more automated. Of course this could also be language specific (or even stub specific) but that would just probably mean more work and mistakes. 

That's why i would propose using UNSUPPORTED (or usage) _but if that is not wanted_ - It would not have to be done this way for every stub(for example if it is too difficult) - _well in that case i guess it gotta be done a little bit differently then_.

**Comment by ikisusi** [comment]
> not so good because java Run.java or something might return the same exit value as well

Hmmm, currently we count on the runner getting the proper exit value from the stub?

But back to the original point. I was trying to say that starting to require returning something specific or `UNSUPPORTED` beyond current calling conventions would require extending the current calling convention, make it and resulting stub code potentially more complex. It might be a slippery road. As you point out it is important that if unexpected things happen there is an expected behaviour, currently it should be that the magic values (VERIFY SUCCESS, VERIFY FAILURE, UNSUPPORTED) are **not** returned and exit value is **not** zero.

**Comment by aleksiklasila** [comment]
In a nutshell i just mean that all the stubs do not print UNSUPPORTED when [... the example has not implemented the requested behavior (e.g. setting CA certificate bundle)] is not satisfied, e.g. wrong number of arguments were given (?). Why would it increase the complexity to check if supported number of arguments were given and if not then print UNSUPPORTED and exit with the value zero. My point is it may not be enough only to return 0 (which, even some of the stubs do not do at the moment) in some cases, but it most definitely would be enough to print (at least ) UNSUPPORTED (that would separate the correct files from the incorrect ones - the executable ones from the others). Obviously if we know the exact name (and 'usage') of a stub (Run or run.py or Run.py or Run.cs (and so on)) for sure this would not be required - but that might not always necessarily be the case - at least in the future. Basically it is just about modifying the current stubs to follow the calling convention (part of which - if i understood correctly - is the following: 'print' UNSUPPORTED and 'return' 0 if wrong number of arguments were given, i.e. the stub could not implement the requested behavior)

I am not talking anything about any other kind of unexpected behavior but just the wrong (UNSUPPORTED) number of arguments.  Furthermore i do not take a stand on other kind of unexpected behaviors or errors in this issue as some of you seem to be implying. It is simply an issue of modifying the current stubs to follow the calling convention, i.e. print UNSUPPORTED and exit with the value zero when unsupported number of arguments were given.

**Comment by jviide** [comment]
The calling convention is documented in [`stubs/README.md`](https://github.com/ouspg/trytls/blob/master/stubs/README.md): If a stub doesn't support setting the CA bundle then it should print UNSUPPORTED and return with exit value 0. If some stub doesn't implement the calling convention, then the stub should be fixed.

**Comment by Mamietti** [comment]
UNSUPPORTED + optional usage is the way to go. You can always provide the context if you want to but it's not required and hence we are definitely not asking too much. Besides UNSUPPORTED was reserved for that purpose anyway (wrong amount of args).

**Comment by aleksiklasila** [comment]
UNSUPPORTED and process exit value zero if calling convention not violated but (number of) arguments still not supported. Otherwise (optional) error and process exit value other than zero.
